export const EN = {
  title: 'User Console',
  subtitle: 'Your account dashboard and token management',
  header: {
    eyebrow: 'User Workspace',
    currentView: 'Current View',
    session: 'Signed in as',
    adminLabel: 'Admin',
    adminMenuAction: 'Admin dashboard',
    logout: 'Sign out',
    loggingOut: 'Signing out…',
    logoutFailed: 'Failed to sign out: {message}',
    unknownUser: 'Connected user',
    views: {
      dashboard: 'Account Overview',
      tokens: 'Token List',
      tokenDetail: 'Token Detail',
    },
    providers: {
      linuxdo: 'LinuxDo',
    },
  },
  dashboard: {
    usage: 'Account Usage Overview',
    description: 'Track account-level throughput, failures, and quota windows without switching pages.',
    dailySuccess: 'Daily Success',
    dailyFailure: 'Daily Failure',
    monthlySuccess: 'Monthly Success',
    monthlySuccessUtc: 'Monthly Success (UTC)',
    hourlyAny: 'Hourly Any Requests',
    hourly: 'Hourly Quota',
    daily: 'Daily Quota',
    monthly: 'Monthly Quota',
  },
  recharge: {
    title: 'Credit Recharge',
    description: 'Add Linux.do Credit quota packages to this account for the current and upcoming natural months.',
    enabled: 'Available',
    disabled: 'Unavailable',
    currentEntitlement: 'Purchased quota this month',
    effectiveUntil: 'Effective until',
    noEntitlement: 'No active package',
    credits: 'Credits',
    months: 'Natural months',
    quotaDelta: 'Quota increase',
    hourlyDelta: 'Hourly',
    dailyDelta: 'Daily',
    monthlyDelta: 'Monthly',
    testPrice: 'Test pricing is enabled: adds one 1 LDC option for 1 credit in 1 month.',
    amount: 'Payment amount',
    preview: 'Preview',
    previewTitle: 'Order impact preview',
    previewDescription: 'Review how this recharge changes quota by month before creating an order.',
    previewScopeNote: 'This preview only shows recharge quota. It does not include or change the account’s own base quota.',
    previewMonth: 'Month',
    previewCurrentQuota: 'Current recharge quota',
    previewDelta: 'Change',
    previewExpectedQuota: 'Expected recharge quota',
    previewAfterExpiry: 'After expiry',
    closePreview: 'Close',
    create: 'Create order',
    creating: 'Creating…',
    createFailed: 'Failed to create order: {message}',
    unavailable: 'Recharge is not configured on this server.',
    orders: 'Recent orders',
    noOrders: 'No recharge orders yet.',
    status: {
      pending: 'Pending',
      paid: 'Paid',
      failed: 'Failed',
    },
  },
  tokens: {
    title: 'Token List',
    description: 'Copy tokens, review quota windows, and open recent request details.',
    loading: 'Loading token list…',
    empty: 'No token available for this account.',
    copy: 'Copy',
    copied: 'Copied',
    copyFailed: 'Copy failed',
    detail: 'Details',
    reset: 'Reset',
    resetDialog: {
      title: 'Reset Token',
      description: 'This will generate a new full token for {tokenId}. The current token stops working immediately.',
      cancel: 'Cancel',
      confirm: 'Reset',
      running: 'Resetting…',
      failed: 'Failed to reset token: {message}',
    },
    resetResult: {
      title: 'New Token Generated',
      copied: 'The new token was copied to clipboard.',
      copyBlocked: 'Automatic copy was blocked. The new token is selected below for manual copy.',
      fieldLabel: 'New Token',
      close: 'Close',
      copy: 'Copy',
      copyFailed: 'Copy Failed',
    },
    manualCopy: {
      title: 'Manual copy required',
      description: 'This browser blocked automatic copy. The full token is selected below for manual copy.',
      fieldLabel: 'Full Token',
      close: 'Close',
    },
    table: {
      id: 'Token ID',
      quotas: 'Quota Windows',
      stats: 'Usage Stats',
      any: 'Any Req (1h)',
      hourly: 'Hourly',
      daily: 'Daily',
      monthly: 'Monthly',
      dailySuccess: 'Daily Success',
      dailyFailure: 'Daily Failure',
      actions: 'Actions',
    },
  },
  unavailable: {
    title: 'User console unavailable',
    description: 'This server has not enabled user OAuth login, so `/console` cannot load dashboard or token data right now.',
    home: 'Back to Home',
  },
  loggedOut: {
    title: 'You have signed out',
    description: 'Sign in again to view your dashboard and token data.',
    action: 'Sign in with LinuxDo',
  },
  loginRequired: {
    title: 'Sign in to open your console',
    description: 'Dashboard and token data appear here after you sign in with LinuxDo.',
    action: 'Sign in with LinuxDo',
  },
  detail: {
    title: 'Token Detail',
    subtitle: 'Review this token’s quota, secret, connectivity checks, and recent requests.',
    subtitleShort: 'Quota, secret, checks, and requests.',
    back: 'Back to Token List',
    backShort: 'Back',
    tokenLabel: 'Token',
    tokenSecret: {
      show: 'Show full token',
      hide: 'Hide full token',
      iconAlt: 'token visibility toggle',
      loading: 'Loading full token…',
      revealFailed: 'Failed to reveal token: {message}',
    },
    guideToken: {
      show: 'Show token',
      hide: 'Hide token',
      loading: 'Loading token…',
      revealFailed: 'Failed to reveal guide token: {message}',
    },
    probe: {
      title: 'Connectivity Checks',
      costHint: "This check uses this token's own quota/credits.",
      costHintAria: 'Quota usage hint',
      mcpButton: {
        idle: 'Test MCP',
        success: 'MCP Ready',
        partial: 'MCP Partial',
        failed: 'MCP Failed',
      },
      apiButton: {
        idle: 'Test API',
        success: 'API Ready',
        partial: 'API Partial',
        failed: 'API Failed',
      },
      runningButton: '{label} {done}/{total}',
      running: 'Checking: {step}',
      preflightFailed: 'Cannot load token secret: {message}',
      summarySuccess: '{passed}/{total} checks passed',
      summaryPartial: '{passed}/{total} checks passed, {failed} failed',
      stepOk: 'OK',
      stepStatus: {
        running: 'Running',
        success: 'Success',
        failed: 'Failed',
        blocked: 'Blocked',
        skipped: 'Skipped',
      },
      quotaBlocked: '{window} quota exhausted, skipping billable MCP tool calls.',
      quotaWindows: {
        hour: 'Hourly',
        day: 'Daily',
        month: 'Monthly',
      },
      bubbles: {
        mcpTitle: 'MCP Probe',
        apiTitle: 'API Probe',
        current: 'Current',
        result: 'Result',
        preflight: 'Token Secret',
        done: 'Summary',
      },
      steps: {
        mcpInitialize: 'MCP session initialize',
        mcpInitialized: 'MCP initialized notification',
        mcpPing: 'MCP service connectivity',
        mcpToolsList: 'MCP tool discovery',
        mcpToolCall: 'Call {tool} tool',
        apiSearch: 'Web search capability',
        apiExtract: 'Page extract capability',
        apiCrawl: 'Site crawl capability',
        apiMap: 'Site map capability',
        apiResearch: 'Research task creation',
        apiResearchResult: 'Research result query',
      },
      skippedProbeFixture: 'No local probe fixture for {tool}; skipped.',
      errors: {
        missingAdvertisedTools: 'MCP tools/list returned no tools',
        missingRequestId: 'Research request_id is missing',
        researchFailed: 'Research task failed',
        researchUnexpectedStatus: 'Research returned unsupported status: {status}',
      },
      researchPendingAccepted: 'pending (accepted)',
      researchStatus: 'status={status}',
    },
    logs: 'Recent Requests (20)',
    pushStatus: {
      ariaLabel: 'Real-time request log push status',
      browserUnsupported:
        'Real-time request log push is unavailable because this browser does not support server-sent events.',
      reconnecting:
        'Real-time request log push is reconnecting. Recent request updates may lag until the stream resumes.',
      closed: 'Real-time request log push connection is unavailable. Refresh the page or try again later.',
    },
    emptyLogs: 'No recent requests.',
    guideTitle: 'Client Setup',
    guideDescription: 'Use the same MCP configuration as the public homepage.',
    guideToggleShow: 'Open setup guide',
    guideToggleHide: 'Close setup guide',
    table: {
      request: 'Request',
      transport: 'HTTP / Tavily',
      path: 'Path',
      time: 'Time',
      http: 'HTTP',
      mcp: 'Tavily',
      credits: 'Credits',
      result: 'Result',
      error: 'Error',
    },
    noQuery: 'No query string',
    noError: 'No error message',
  },
  errors: {
    load: 'Failed to load console data',
    detail: 'Failed to load token detail',
  },
  footer: {
    title: 'Tavily Hikari User Console',
    githubAria: 'Open GitHub repository',
    githubLabel: 'GitHub',
    loadingVersion: '· Loading version…',
    errorVersion: '· Version unavailable',
    tagPrefix: '· ',
  },
}

export const ZH = {
  title: '用户控制台',
  subtitle: '账户仪表盘与 Token 管理',
  header: {
    eyebrow: '用户工作区',
    currentView: '当前视图',
    session: '当前身份',
    adminLabel: '管理员',
    adminMenuAction: '管理员面板',
    logout: '退出登录',
    loggingOut: '退出中…',
    logoutFailed: '退出登录失败：{message}',
    unknownUser: '已连接用户',
    views: {
      dashboard: '账户概览',
      tokens: 'Token 列表',
      tokenDetail: 'Token 详情',
    },
    providers: {
      linuxdo: 'LinuxDo',
    },
  },
  dashboard: {
    usage: '账户用量概览',
    description: '在同一页集中查看账户级成功率、失败量与各配额窗口。',
    dailySuccess: '今日成功',
    dailyFailure: '今日失败',
    monthlySuccess: '本月成功',
    monthlySuccessUtc: '本月成功（UTC）',
    hourlyAny: '每小时任意请求',
    hourly: '小时配额',
    daily: '日配额',
    monthly: '月配额',
  },
  recharge: {
    title: '积分充值',
    description: '使用 Linux.do Credit 为当前账户购买本月及后续自然月的可用额度。',
    enabled: '可用',
    disabled: '不可用',
    currentEntitlement: '本月已购额度',
    effectiveUntil: '权益有效至',
    noEntitlement: '暂无生效权益',
    credits: '积分额度',
    months: '自然月数',
    quotaDelta: '额度增量',
    hourlyDelta: '小时',
    dailyDelta: '日',
    monthlyDelta: '月',
    testPrice: '测试价格已开启：额外提供 1 LDC 购买 1 个自然月的 1 积分。',
    amount: '支付金额',
    preview: '预览',
    previewTitle: '订单影响预览',
    previewDescription: '创建订单前，查看本次充值会如何影响每个月的额度。',
    previewScopeNote: '这里只展示充值额度，不展示也不影响账号自身基础额度。',
    previewMonth: '月份',
    previewCurrentQuota: '当前充值额度',
    previewDelta: '变化',
    previewExpectedQuota: '预期充值额度',
    previewAfterExpiry: '到期后',
    closePreview: '关闭',
    create: '创建订单',
    creating: '创建中…',
    createFailed: '创建订单失败：{message}',
    unavailable: '当前服务尚未配置充值功能。',
    orders: '近期订单',
    noOrders: '暂无充值订单。',
    status: {
      pending: '待支付',
      paid: '已支付',
      failed: '失败',
    },
  },
  tokens: {
    title: 'Token 列表',
    description: '复制 Token、查看配额窗口，并进入详情检查最近请求。',
    loading: 'Token 列表加载中…',
    empty: '当前账户暂无 Token。',
    copy: '复制',
    copied: '已复制',
    copyFailed: '复制失败',
    detail: '详情',
    reset: '重置',
    resetDialog: {
      title: '重置 Token',
      description: '这会为 {tokenId} 生成新的完整 Token，当前 Token 会立即失效。',
      cancel: '取消',
      confirm: '重置',
      running: '重置中…',
      failed: '重置 Token 失败：{message}',
    },
    resetResult: {
      title: '新 Token 已生成',
      copied: '新的 Token 已复制到剪贴板。',
      copyBlocked: '当前浏览器拦截了自动复制，下面已选中新 Token，可直接手动复制。',
      fieldLabel: '新 Token',
      close: '关闭',
      copy: '复制',
      copyFailed: '复制失败',
    },
    manualCopy: {
      title: '请手动复制',
      description: '当前浏览器拦截了自动复制，下面已选中完整 Token，可直接手动复制。',
      fieldLabel: '完整 Token',
      close: '关闭',
    },
    table: {
      id: 'Token ID',
      quotas: '配额窗口',
      stats: '用量统计',
      any: '任意请求(1h)',
      hourly: '小时',
      daily: '日',
      monthly: '月',
      dailySuccess: '今日成功',
      dailyFailure: '今日失败',
      actions: '操作',
    },
  },
  unavailable: {
    title: '用户控制台暂不可用',
    description: '当前服务未启用用户 OAuth 登录，因此 `/console` 暂时无法加载账户仪表盘与 Token 数据。',
    home: '返回首页',
  },
  loggedOut: {
    title: '你已退出登录',
    description: '重新登录后即可查看账户仪表盘与 Token 数据。',
    action: '使用 LinuxDo 登录',
  },
  loginRequired: {
    title: '登录后即可打开控制台',
    description: '使用 LinuxDo 登录后，这里就会显示你的仪表盘与 Token 数据。',
    action: '使用 LinuxDo 登录',
  },
  detail: {
    title: 'Token 详情',
    subtitle: '查看当前 Token 的配额、密钥、连通性检测与最近请求。',
    subtitleShort: '查看配额、密钥、检测与请求。',
    back: '返回 Token 列表',
    backShort: '返回',
    tokenLabel: 'Token',
    tokenSecret: {
      show: '显示完整 Token',
      hide: '隐藏完整 Token',
      iconAlt: 'Token 显隐切换',
      loading: '正在读取完整 Token…',
      revealFailed: '读取完整 Token 失败：{message}',
    },
    guideToken: {
      show: '显示密钥',
      hide: '隐藏密钥',
      loading: '正在读取密钥…',
      revealFailed: '读取导览密钥失败：{message}',
    },
    probe: {
      title: '连通性检测',
      costHint: '该检测会消耗当前 Token 自身额度。',
      costHintAria: '额度消耗提示',
      mcpButton: {
        idle: '检测 MCP',
        success: 'MCP 就绪',
        partial: 'MCP 部分通过',
        failed: 'MCP 失败',
      },
      apiButton: {
        idle: '检测 API',
        success: 'API 就绪',
        partial: 'API 部分通过',
        failed: 'API 失败',
      },
      runningButton: '{label} {done}/{total}',
      running: '检测中：{step}',
      preflightFailed: '读取 Token 失败：{message}',
      summarySuccess: '{passed}/{total} 项通过',
      summaryPartial: '{passed}/{total} 项通过，{failed} 项失败',
      stepOk: '通过',
      stepStatus: {
        running: '进行中',
        success: '成功',
        failed: '失败',
        blocked: '受阻',
        skipped: '已跳过',
      },
      quotaBlocked: '{window}配额已耗尽，已跳过会消耗额度的 MCP 工具调用。',
      quotaWindows: {
        hour: '小时',
        day: '日',
        month: '月',
      },
      bubbles: {
        mcpTitle: 'MCP 检测',
        apiTitle: 'API 检测',
        current: '当前检测',
        result: '结果',
        preflight: '读取 Token',
        done: '汇总',
      },
      steps: {
        mcpInitialize: 'MCP 会话初始化',
        mcpInitialized: 'MCP initialized 通知',
        mcpPing: 'MCP 服务连通',
        mcpToolsList: 'MCP 工具发现',
        mcpToolCall: '调用 {tool} 工具',
        apiSearch: '网页搜索能力',
        apiExtract: '页面抽取能力',
        apiCrawl: '站点抓取能力',
        apiMap: '站点映射能力',
        apiResearch: '研究任务创建',
        apiResearchResult: '研究结果查询',
      },
      skippedProbeFixture: '当前本地没有 {tool} 的检测夹具，已跳过。',
      errors: {
        missingAdvertisedTools: 'MCP tools/list 没有返回任何工具',
        missingRequestId: 'research 响应缺少 request_id',
        researchFailed: 'research 任务失败',
        researchUnexpectedStatus: 'research 返回了不支持的状态：{status}',
      },
      researchPendingAccepted: 'pending（已受理）',
      researchStatus: '状态={status}',
    },
    logs: '近期请求（20 条）',
    pushStatus: {
      ariaLabel: '实时请求日志推送状态',
      browserUnsupported: '当前浏览器不支持服务器推送事件，实时请求日志推送不可用。',
      reconnecting: '实时请求日志推送正在重连，恢复前最近请求列表可能会有延迟。',
      closed: '实时请求日志推送连接当前不可用，请刷新页面或稍后再试。',
    },
    emptyLogs: '暂无请求记录。',
    guideTitle: '客户端接入',
    guideDescription: '沿用首页的 MCP 配置方式即可接入。',
    guideToggleShow: '展开接入指南',
    guideToggleHide: '收起接入指南',
    table: {
      request: '请求',
      transport: 'HTTP / Tavily',
      path: '路径',
      time: '时间',
      http: 'HTTP',
      mcp: 'Tavily',
      credits: '积分',
      result: '结果',
      error: '错误',
    },
    noQuery: '无查询参数',
    noError: '无错误信息',
  },
  errors: {
    load: '加载控制台数据失败',
    detail: '加载 Token 详情失败',
  },
  footer: {
    title: 'Tavily Hikari 用户控制台',
    githubAria: '打开 GitHub 仓库',
    githubLabel: 'GitHub',
    loadingVersion: '· 正在读取版本…',
    errorVersion: '· 版本不可用',
    tagPrefix: '· ',
  },
}
